#!/bin/bash

if [ -z "$IDF_PATH" ]
then
    echo "Must set IDF_PATH" 1>&2
    exit 1
fi

if [ -d /project ]
then
    # fix for github build action
    git config --global --add safe.directory /project
fi

if [ $# -eq 0 ]
then
    if [ -n "$ESP32_TARGETS" ]
    then
	TARGET=( "$ESP32_TARGETS" )
    else
	TARGET=$(idf.py --list-targets)
    fi
else
    TARGET=( "$@" )
fi

rm -rf built-*

for target in ${TARGET[@]}
do
    case $target in
	esp32|esp32s*)
	               arch=xtensa
		       subarch=$target
		       ;;
	esp32c*|esp32h*)
	               arch=riscv32
		       subarch=esp
		       ;;
    esac

    mkdir built-${target}
    IDF="idf.py -B built-${target}"

    set -ex
    echo "Building for ${arch}...."
    rm -rf sdkconfig
    $IDF set-target $target
    $IDF fullclean
    $IDF build 2>&1 | ${arch}-${subarch}-elf-c++filt
    set +ex
done
