/*
 * SPDX-License-Identifier: GPL-2.0-only
 */

typedef enum
{
  PRI_IDLE = 5,
  PRI_GPIO,
  PRI_DEBOUNCE,
  PRI_ADC,
  PRI_ADC_SPEED,
  PRI_BATTERY_MONITOR,
  PRI_NETWORK_CONN,
  PRI_WIFI_CONTROLLER,
  PRI_MDNS_CONTROLLER,
  PRI_THROTTLE_CONTROLLER,
  PRI_LOGGER,
  PRI_BLUETOOTH_CONTROLLER,
  PRI_CMDLINE,
  PRI_PILOT_LIGHT,
} bkt_priority;
